name: build and test

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install Nix
      uses: cachix/install-nix-action@v31
    - name: get repo
      run: git clone --single-branch -b anilibria-winmaclinux --depth 1 https://github.com/3JlOy-PYCCKUi/nixpkgs
    - name: show current commit
      run: pushd nixpkgs && git log --oneline HEAD && popd
    - name: build
      run: pushd nixpkgs && nix-build -A anilibria-winmaclinux && popd
    - name: run with timout
      run: nix develop github:nixos/nixpkgs/nixos-unstable#coreutils --command timeout 10 nixpkgs/result/bin/AniLiberty || true
